### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [rust-keylock/rust-keylock-android#3]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by astonbitecode** [comment]
Thanks for that. Will do in the next release... Hopefully in a few days.

**Comment by mondlicht-und-sterne** [comment]
thank you very much

**Comment by astonbitecode** [comment]
[Done](https://f-droid.org/en/packages/org.astonbitecode.rustkeylock/). The description is mistakenly overridden by the `yml` on the fdroid repo, but this (along with some formatting improvements) can be fixed in the next release, when a new merge request will be submitted to f-droid.

Anyway, the images are already there, so I guess this can be closed.
